### ISSUE TITLE
Possible merge between CookieMonster and achievement unhider

### ISSUE THREAD

**Issue by DanielNoord** [Rjlintkh/Cookie-Clicker-CPS-Counter#1]
Per your message on reddit.

I like the unhider you have made and think it fits well with the other functions of CookieMonster. However, I am not really in favour of loading your mod through CookieMonster and would like the function to be part of CookieMonster's codebase. This would require some modifications to the code in order to make it more like the other functions in our code, such as `CM.Disp.AddMissingUpgrades` found in `src/Disp.js`.
Two of the biggest changes would be to not change Game code directly, but to make a CookieMonster implementation that is based of the Game code, and to make the function toggleable.
If you want to take on this project I would be more than happy to assist and answer any questions along the way. If not, I might return to this feature but will probably not add it in the near future.

**Comment by Rjlintkh** [comment]
I would like it to be a part of CookieMonster, not a separate addon too. And making it toggleable is easy (by backing up the function and replace it again to revert it), however not changing the game code directly is hard for me.

Unhiding achievement is not the same as CM.Disp.AddMissingUpgrades, it's not appending new HTML elements but it's changing variables before loading the HTML elements

**Comment by DanielNoord** [comment]
I think it would be better to make the toggle work with an if-statement that checks how the achievements should be drawn. 

There is indeed a difference between both functions. Perhaps making it so that we back-up the original code in a backup function is the best solution (you can see this in the functions that overwrite building tooltips). As then it is clearer that the code is not original but actually changed by CookieMonster.

**Comment by Rjlintkh** [comment]
Could you tell me which lines or functions are for overwritting building tooltips? Currently I am working on having a variable to state if mysterious normal achievements or mysterious shadow achievements should be unhidden or both of them should be unhidden.

**Comment by DanielNoord** [comment]
See `CM.Disp.ReplaceTooltipBuild` at line 1189 of `Disp.js` and the functions that follow in the successive lines.

**Comment by Rjlintkh** [comment]
Found it, but are they used later or just backed up for unexpected things?

**Comment by DanielNoord** [comment]
They are not, but we think it is good practice to do this. It does not impact the size of used memory significantly.

**Comment by Rjlintkh** [comment]
I have made a new version of it, https://github.com/Rjlintkh/Cookie-Clicker-CPS-Counter/commit/c725066d6163256b010445532f889762b77f8a04
Hope you have a look on it :D
Functions and variables are said in the commit description.
Functions are backed up inside an array.

**Comment by DanielNoord** [comment]
Perhaps it is best to make a draft PR on the CookieMonster repository because then we can also immediately integrate it into the settings of CookieMonster and I can comment on that. And by doing that I can comment on the code which I can't right now.

For now:
The biggest issue I have is that we add 230 lines of code that originate from the Game code to change 9 lines. There are two possible solutions:
1) Overwriting the `.onmouseover` and draw functions of achievements in the stats page to point to functions that we wrote specifically for them. This would allow use to remove unnecessary lines such as 126-165 in the new file and make the code much cleaner.
2) Overwrite certain lines of the original function with `.replace()` or a similar function by searching/selecting (possibly with regex) for the lines to be overwritten.

I am not quite sure which I would prefer but I think solution 1 would create code that is most understandable for new contributors. CookieMonster relies on contributors that often come and go (as the game does not entertain most people for longer than a couple of weeks) and therefore making understandable and easy to read code is crucial. Adding 221 unnecessary lines would therefore not be in the interest of the project.

**Comment by Rjlintkh** [comment]
I would prefer the second solution more since the variables are created inside the function, I cannot edit them outside the function.
I will draft a pull request on the CookieMonster repo once I complete it.

**Comment by Rjlintkh** [comment]
Oh I understand what you mean by the first solution now, I misunderstood it, I also agree on it now.

**Comment by DanielNoord** [comment]
I think for the PR on the CookieMonster repo it is important to first add the option to the settings, as this creates the variables that need to be checked before any code (tooltips or crate) is changed. You can do this by adding additional options to the `Data.js` file. A quick inspection of that code should hopefully explain how it works (don't forget to add a standard setting).

**Comment by Rjlintkh** [comment]
Did it!

**Comment by Rjlintkh** [comment]
I actually have exams tomorrow so maybe I cannot reply quickly, sorry for that
